version: '3.7'

services:
  # ---------------------------------------------------
  postgres:
    image: postgres:13
    ports:
      - 9001:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=manny
      - POSTGRES_PASSWORD=change-in-production
      - POSTGRES_DB=brain
  # ---------------------------------------------------


volumes:
  postgres_data:
